# Site settings
title: JobTeaser Career
email: recrutement@jobteaser.com
description: > # this means to ignore newlines until "baseurl:"
  JobTeaser Career Website for tech
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://career.jobteaser.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
